language: go

matrix:
  fast_finish: true
  include:
    - go: 1.14.x
      env:
        - TESTTAGS=nomsgpack
        - MONGO_HOST=127.0.0.1
        - MONGO_PORT=27017
        - MONGO_USERNAME=root
        - MONGO_PASSWORD=root
    - go: master
      env:
        - TESTTAGS=nomsgpack
        - MONGO_HOST=127.0.0.1
        - MONGO_PORT=27017
        - MONGO_USERNAME=root
        - MONGO_PASSWORD=root

git:
  depth: 10

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
services:
  - docker
  - mongodb

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

go_import_path: github.com/yongliu1992/todo

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"root",pwd:"root",roles:["readWrite"]});'

script:
  - make vet
  - make fmt-check
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
